name: firestore_cache_manager
description: A package which makes Firestore be able to manage cache expiration.
version: 0.1.0
author: Ryunosuke Watanabe
homepage: https://github.com/HeavenOSK/flutter_firestore_cache_manager

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.5
  shared_preferences: ^0.5.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.9.1
flutter:
